<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>GastroTrack - Expiry Calendar</title>

  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="css/variables.css">
  <link rel="stylesheet" href="css/dashboard.css">
  <link rel="stylesheet" href="css/expiry-calendar.css">
</head>
<body>
  
  <!-- SIDEBAR -->
  <aside class="sidebar">
    <div class="brand">
      <div class="logo" aria-hidden="true"><span style="font-size:28px">👨🏻‍🍳</span></div>
      <span>GastroTrack</span>
    </div>

    <nav class="nav" aria-label="Main navigation">
      <a href="dashboard.php"><span>Dashboard</span></a>
      <a href="inventory.php"><span>Inventory</span></a>
      <a class="active" href="expiry-calendar.php"><span>Expiry Calendar</span></a>
      <a href="sales-report.php"><span>Sales Report</span></a>
      <a href="cost-waste.php"><span>Cost & Waste</span></a>
      <a href="suggestions.php"><span>Suggestions</span></a>
      <a href="menu-insights.php"><span>Menu Insights</span></a>
    </nav>

    <div class="spacer"></div>
    <nav class="nav">
      <a href="profile.php"><span>Profile</span></a>
      <a href="#" onclick="logout()"><span>Log Out</span></a>
    </nav>
  </aside>

  <!-- MAIN -->
  <main class="main">
    <!-- Calendar Section -->
    <section class="calendar-section">
      <div class="calendar-header">
        <h1 id="currentMonth">September 2025</h1>
        <div class="calendar-nav">
          <button class="nav-btn" onclick="previousMonth()" aria-label="Previous month">&lt;</button>
          <button class="nav-btn" onclick="nextMonth()" aria-label="Next month">&gt;</button>
        </div>
      </div>

      <div class="calendar-grid">
        <!-- Day headers -->
        <div class="day-header">Sun</div>
        <div class="day-header">Mon</div>
        <div class="day-header">Tues</div>
        <div class="day-header">Wed</div>
        <div class="day-header">Thurs</div>
        <div class="day-header">Fri</div>
        <div class="day-header">Sat</div>

        <!-- Calendar days will be generated by JavaScript -->
        <div id="calendarDays"></div>
      </div>
    </section>

    <!-- Expiry Alerts Section -->
    <section class="expiry-alerts-section">
      <div class="alerts-grid">
        <!-- Critical - 1 day -->
        <div class="expiry-item expiry-critical">
          <div class="expiry-content">
            <strong>Milk (8L)</strong> expiring in <strong>1 day(s)</strong> (Sept 2)
          </div>
        </div>

        <div class="expiry-item expiry-critical">
          <div class="expiry-content">
            <!-- Placeholder for more critical items -->
          </div>
        </div>

        <!-- Warning - 2 days -->
        <div class="expiry-item expiry-warning">
          <div class="expiry-content">
            <strong>Avocado (2.3KG)</strong> expiring in <strong>2 day(s)</strong> (Sept 3)
          </div>
        </div>

        <div class="expiry-item expiry-warning">
          <div class="expiry-content">
            <!-- Placeholder for more warning items -->
          </div>
        </div>

        <!-- Caution - 3-7 days -->
        <div class="expiry-item expiry-caution">
          <div class="expiry-content">
            <!-- Placeholder -->
          </div>
        </div>

        <div class="expiry-item expiry-caution">
          <div class="expiry-content">
            <!-- Placeholder -->
          </div>
        </div>

        <div class="expiry-item expiry-caution">
          <div class="expiry-content">
            <!-- Placeholder -->
          </div>
        </div>

        <div class="expiry-item expiry-caution">
          <div class="expiry-content">
            <!-- Placeholder -->
          </div>
        </div>
      </div>
    </section>
  </main>

  <!-- Logout script -->
  <script>
    function logout() {
      console.log('Logout function called');
      localStorage.removeItem('userID');
      alert('Logged out successfully!');
      window.location.href = 'loginpage.php';
      return false;
    }
    
    // Check auth on page load
    window.onload = function() {
      var userId = localStorage.getItem('userID');
      console.log('Page loaded, userID:', userId);
      
      if (!userId || userId.trim() === '') {
        console.log('No userID found, redirecting to login');
        window.location.href = 'loginpage.php';
        return;
      }
      
      console.log('User authenticated, page ready');
      
      // Initialize calendar
      renderCalendar();
    };
  </script>
  
  <script src="js/expiry-calendar.js"></script>
</body>
</html>

